# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=250)),
                ('Last_Name', models.CharField(max_length=250)),
                ('Adress', models.CharField(max_length=300)),
                ('Phone', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254)),
                ('Marital_Status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('E', 'Engaged')], max_length=1)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Believer', models.BooleanField()),
                ('Registered', models.BooleanField()),
                ('Branch', models.CharField(max_length=300)),
                ('Date_registered', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
